disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Yuki Shiroi"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
#   dateFormat = "2 January 2006"
  # logo = "img/d.jpg"
   secondaryLogo = "img/d.jpg"
  # description = "My awesome website"
  copyright = "&copy; 2024 Yuki Shiroi. All right reserved."

 [params.author]
   name = "Yuki Shiroi"
   email = "voquangvu09112006@gmail.com"
   image = "img/d.jpg"
   imageQuality = 96
   headline = "a.k.a winky"
   bio =  "If strength is justice, then is powerlessness a crime?" 
   links = [
     { email = "mailto:hello@voquangvu09112006@gmail.com" },
     { link = "https://winky9116.github.io" },
    #  { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    #  { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/threalwinky" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/threalwinky" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
    { spotify = "https://open.spotify.com/user/317kafuqbev46sq43z2u3zjjbpym" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
